server {
    listen 80;
    server_name _;

    access_log /var/log/nginx/access.log combined;
    error_log /var/log/nginx/error.log warn;

    location = / {
        add_header Content-Type text/plain;
        return 200 "SO ELK demo: página inicial\n";
    }

    location /login {
        add_header Content-Type text/plain;
        return 200 "SO ELK demo: login fake\n";
    }

    location /admin-falso {
        add_header Content-Type text/plain;
        return 403 "SO ELK demo: acesso negado\n";
    }

    location /erro-500 {
        add_header Content-Type text/plain;
        return 500 "SO ELK demo: erro proposital\n";
    }
}
