input {
  beats {
    port => 5044
  }
}

filter {
  if [fields][log_type] == "nginx_access" {
    grok {
      match => { "message" => "%{COMBINEDAPACHELOG}" }
    }
    mutate {
      convert => {
        "response" => "integer"
        "bytes" => "integer"
      }
      add_field => { "event.dataset" => "nginx.access" }
    }
  } else if [fields][log_type] == "simulated_auth" {
    grok {
      match => {
        "message" => [
          "%{SYSLOGTIMESTAMP:syslog_timestamp} %{HOSTNAME:host_name} sshd\[%{POSINT:pid}\]: Failed password for invalid user %{USERNAME:user} from %{IP:source_ip} port %{POSINT:source_port} ssh2",
          "%{SYSLOGTIMESTAMP:syslog_timestamp} %{HOSTNAME:host_name} sshd\[%{POSINT:pid}\]: Accepted password for %{USERNAME:user} from %{IP:source_ip} port %{POSINT:source_port} ssh2",
          "%{SYSLOGTIMESTAMP:syslog_timestamp} %{HOSTNAME:host_name} sudo: +%{USERNAME:user} : TTY=%{DATA:tty} ; PWD=%{DATA:pwd} ; USER=%{USERNAME:sudo_user} ; COMMAND=%{GREEDYDATA:command}"
        ]
      }
    }
    mutate {
      add_field => { "event.dataset" => "linux.auth" }
    }
  } else if [fields][log_type] == "simulated_syslog" {
    grok {
      match => {
        "message" => [
          "%{SYSLOGTIMESTAMP:syslog_timestamp} %{HOSTNAME:host_name} %{DATA:service}\[%{POSINT:pid}\]: %{LOGLEVEL:log_level}: %{GREEDYDATA:syslog_message}",
          "%{SYSLOGTIMESTAMP:syslog_timestamp} %{HOSTNAME:host_name} kernel: \[%{DATA:kernel_time}\] %{LOGLEVEL:log_level}: %{GREEDYDATA:syslog_message}",
          "%{SYSLOGTIMESTAMP:syslog_timestamp} %{HOSTNAME:host_name} systemd\[%{POSINT:pid}\]: %{GREEDYDATA:syslog_message}"
        ]
      }
    }
    mutate {
      add_field => { "event.dataset" => "linux.syslog" }
    }
  } else if [fields][log_type] == "simulated_app" {
    json {
      source => "message"
      target => "app"
    }
    mutate {
      add_field => { "event.dataset" => "app.api" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "so-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
